# fly.toml app configuration file generated for dieting-app on 2026-06-27T20:50:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dieting-app'
primary_region = 'iad'

[build]

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ConnectionStrings__Db = 'Data Source=/app/data/DietPlannerDatabase.db'
  DataProtectionKeysPath = '/app/data/keys'

[[mounts]]
  source = 'dietplanner_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
