// <auto-generated />
using System;
using DietPlanner;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("DietPlanner.Endpoints.Meal.MealEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarbsG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FibreG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kcal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MfName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Plants")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProteinG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZoeNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SlotKey");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("DietPlanner.Endpoints.Meal.MealIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MealId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("MealIngredients");
                });

            modelBuilder.Entity("DietPlanner.Endpoints.Settings.Settings", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DietPlanner.Endpoints.Slots.Slot", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("DietPlanner.Endpoints.WeekPlan.WeekPlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MealId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PortionMultiplier")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("SlotKey");

                    b.HasIndex("Date", "SlotKey")
                        .IsUnique();

                    b.ToTable("WeekPlanEntries");
                });

            modelBuilder.Entity("DietPlanner.Endpoints.Meal.MealEntry", b =>
                {
                    b.HasOne("DietPlanner.Endpoints.Slots.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("DietPlanner.Endpoints.Meal.MealIngredient", b =>
                {
                    b.HasOne("DietPlanner.Endpoints.Meal.MealEntry", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("DietPlanner.Endpoints.WeekPlan.WeekPlanEntry", b =>
                {
                    b.HasOne("DietPlanner.Endpoints.Meal.MealEntry", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DietPlanner.Endpoints.Slots.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("DietPlanner.Endpoints.Meal.MealEntry", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
