using DietPlanner.Endpoints.Meal;
using Microsoft.AspNetCore.Components;
using Microsoft.Extensions.Logging;

namespace DietPlanner.Components.Pages;

public partial class MealUploadPage
{
    [Inject]
    private ILogger<MealUploadPage> Logger { get; set; } = null!;

    // The [LoggerMessage] source generator emits malformed fallback code when its containing
    // partial class also has parts generated by the Razor component compiler, so log directly here.
    private void LogCsvImportFailed(Exception exception, string fileName) =>
        Logger.LogError(exception, "CSV meal import failed for file '{FileName}'", fileName);

    private void LogPdfImportFailed(Exception exception, string fileName) =>
        Logger.LogError(exception, "PDF meal import failed for file '{FileName}'", fileName);
}
